Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  IgnoredMethods:
    - 'scores'
    - 'start_game'

Metrics/MethodLength:
  IgnoredMethods:
    - 'scores'
    - 'start_game'
